---

plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  semi: [error, never]
  # Добавь вот эту строку ниже:
  arrow-parens: [error, as-needed]
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]