name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Test & publish code coverage
        # Используем стандартный способ загрузки через встроенную утилиту
        run: |
          wget -O ./cc-test-reporter https://github.com/codeclimate/test-reporter/releases/download/v0.11.1/test-reporter-0.11.1-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          make test-coverage
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: 299d18e9df944440a7134029477e2e07df3d6c51f35e65155e3a435ad0666c8e