# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Используем стабильную 20-ю версию (24-й еще нет)
      matrix:
        node-version: [20.x]

    steps:
      # Check-out repository (используем стабильную v4)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для глубокого анализа SonarQube

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests and coverage
        run: make test-coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=aleksandra-korza_frontend-project-lvl2
            -Dsonar.organization=aleksandra-korza
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info